// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry.proto

package telemetry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TelemetryMessage struct {
	Timestamp            *uint64  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	Bytes                []byte   `protobuf:"bytes,2,req,name=bytes" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryMessage) Reset()         { *m = TelemetryMessage{} }
func (m *TelemetryMessage) String() string { return proto.CompactTextString(m) }
func (*TelemetryMessage) ProtoMessage()    {}
func (*TelemetryMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{0}
}

func (m *TelemetryMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryMessage.Unmarshal(m, b)
}
func (m *TelemetryMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryMessage.Marshal(b, m, deterministic)
}
func (m *TelemetryMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryMessage.Merge(m, src)
}
func (m *TelemetryMessage) XXX_Size() int {
	return xxx_messageInfo_TelemetryMessage.Size(m)
}
func (m *TelemetryMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryMessage proto.InternalMessageInfo

func (m *TelemetryMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *TelemetryMessage) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type TelemetryMessageLog struct {
	Location             *string             `protobuf:"bytes,1,req,name=location" json:"location,omitempty"`
	SystemId             *string             `protobuf:"bytes,2,req,name=system_id,json=systemId" json:"system_id,omitempty"`
	SourceAddress        *string             `protobuf:"bytes,3,opt,name=source_address,json=sourceAddress" json:"source_address,omitempty"`
	SourcePort           *uint32             `protobuf:"varint,4,opt,name=source_port,json=sourcePort" json:"source_port,omitempty"`
	Message              []*TelemetryMessage `protobuf:"bytes,5,rep,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TelemetryMessageLog) Reset()         { *m = TelemetryMessageLog{} }
func (m *TelemetryMessageLog) String() string { return proto.CompactTextString(m) }
func (*TelemetryMessageLog) ProtoMessage()    {}
func (*TelemetryMessageLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{1}
}

func (m *TelemetryMessageLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryMessageLog.Unmarshal(m, b)
}
func (m *TelemetryMessageLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryMessageLog.Marshal(b, m, deterministic)
}
func (m *TelemetryMessageLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryMessageLog.Merge(m, src)
}
func (m *TelemetryMessageLog) XXX_Size() int {
	return xxx_messageInfo_TelemetryMessageLog.Size(m)
}
func (m *TelemetryMessageLog) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryMessageLog.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryMessageLog proto.InternalMessageInfo

func (m *TelemetryMessageLog) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *TelemetryMessageLog) GetSystemId() string {
	if m != nil && m.SystemId != nil {
		return *m.SystemId
	}
	return ""
}

func (m *TelemetryMessageLog) GetSourceAddress() string {
	if m != nil && m.SourceAddress != nil {
		return *m.SourceAddress
	}
	return ""
}

func (m *TelemetryMessageLog) GetSourcePort() uint32 {
	if m != nil && m.SourcePort != nil {
		return *m.SourcePort
	}
	return 0
}

func (m *TelemetryMessageLog) GetMessage() []*TelemetryMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*TelemetryMessage)(nil), "TelemetryMessage")
	proto.RegisterType((*TelemetryMessageLog)(nil), "TelemetryMessageLog")
}

func init() { proto.RegisterFile("telemetry.proto", fileDescriptor_edbfcf76559f568d) }

var fileDescriptor_edbfcf76559f568d = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x70, 0x76, 0xdb, 0x62, 0x33, 0x6b, 0xfd, 0x13, 0x3d, 0x04, 0x15, 0x0c, 0x05, 0x21,
	0x20, 0xf4, 0xe0, 0x1b, 0xe8, 0x41, 0x10, 0x14, 0x24, 0x78, 0xf2, 0x52, 0x62, 0x33, 0x94, 0x85,
	0xc6, 0x59, 0x32, 0xe3, 0x61, 0x9f, 0xcf, 0x17, 0x13, 0x1a, 0xdb, 0xc2, 0x1e, 0xe7, 0xc7, 0xc7,
	0xc7, 0xc7, 0xc0, 0xa9, 0xe0, 0x06, 0x13, 0x4a, 0xee, 0x17, 0x5d, 0x26, 0xa1, 0xf9, 0x33, 0x9c,
	0x7d, 0xec, 0xe8, 0x0d, 0x99, 0xc3, 0x1a, 0xf5, 0x0d, 0x28, 0x69, 0x13, 0xb2, 0x84, 0xd4, 0x99,
	0xca, 0xd6, 0x6e, 0xec, 0x0f, 0xa0, 0x2f, 0x61, 0xf2, 0xd5, 0x0b, 0xb2, 0xa9, 0x6d, 0xed, 0x8e,
	0x7d, 0x39, 0xe6, 0xbf, 0x15, 0x5c, 0x0c, 0x8b, 0x5e, 0x69, 0xad, 0xaf, 0x60, 0xba, 0xa1, 0x55,
	0x90, 0x96, 0xbe, 0xb7, 0x55, 0xca, 0xef, 0x6f, 0x7d, 0x0d, 0x8a, 0x7b, 0x16, 0x4c, 0xcb, 0x36,
	0x6e, 0xdb, 0x94, 0x9f, 0x16, 0x78, 0x89, 0xfa, 0x0e, 0x4e, 0x98, 0x7e, 0xf2, 0x0a, 0x97, 0x21,
	0xc6, 0x8c, 0xcc, 0x66, 0x64, 0x2b, 0xa7, 0xfc, 0xac, 0xe8, 0x63, 0x41, 0x7d, 0x0b, 0xcd, 0x7f,
	0xac, 0xa3, 0x2c, 0x66, 0x6c, 0x2b, 0x37, 0xf3, 0x50, 0xe8, 0x9d, 0xb2, 0xe8, 0x7b, 0x38, 0x4a,
	0x65, 0x8e, 0x99, 0xd8, 0x91, 0x6b, 0x1e, 0xce, 0x17, 0xc3, 0x9d, 0x7e, 0x97, 0x78, 0x6a, 0x3e,
	0xd5, 0xfe, 0x41, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x02, 0xbd, 0x2a, 0x2c, 0x01, 0x00,
	0x00,
}
